package com.cpz.sim.datacenter.snapshot;

import java.util.List;
import java.util.Objects;

/**
 * Represents the aggregated cooling result of a group of cooling zones at a
 * simulation tick.
 *
 * <p>This snapshot is intended for consumers that need a higher-level view over
 * several logical zones, such as a hot aisle, a room section, or any external
 * grouping defined by an adapter or UI.</p>
 *
 * @param groupCode external group code
 * @param zoneCodes cooling-zone codes included in the group
 * @param generatedHeatWatts total heat generated by the grouped zones
 * @param availableCoolingCapacityWatts total cooling capacity available to the grouped zones
 * @param usedCoolingCapacityWatts total cooling capacity used by the grouped zones
 * @param coolingDeficitWatts total uncovered thermal load
 * @param averageInletAirTemperatureCelsius average inlet-air temperature
 * @param averageExhaustAirTemperatureCelsius average exhaust-air temperature
 * @param averageRecirculationFraction average recirculation fraction
 *
 * @author CPZ
 */
public record CoolingZoneGroupSnapshot(
        String groupCode,
        List<String> zoneCodes,
        double generatedHeatWatts,
        double availableCoolingCapacityWatts,
        double usedCoolingCapacityWatts,
        double coolingDeficitWatts,
        double averageInletAirTemperatureCelsius,
        double averageExhaustAirTemperatureCelsius,
        double averageRecirculationFraction
) {

    public CoolingZoneGroupSnapshot {
        Objects.requireNonNull(groupCode, "groupCode must not be null");
        Objects.requireNonNull(zoneCodes, "zoneCodes must not be null");
        if (groupCode.isBlank()) throw new IllegalArgumentException("groupCode must not be blank");
        if (zoneCodes.isEmpty()) throw new IllegalArgumentException("zoneCodes must not be empty");
        if (zoneCodes.stream().anyMatch(Objects::isNull)) throw new NullPointerException("zoneCodes must not contain null");
        if (zoneCodes.stream().anyMatch(String::isBlank)) throw new IllegalArgumentException("zoneCodes must not contain blank values");
        validateNonNegativeFinite(generatedHeatWatts, "generatedHeatWatts");
        validateNonNegativeFinite(availableCoolingCapacityWatts, "availableCoolingCapacityWatts");
        validateNonNegativeFinite(usedCoolingCapacityWatts, "usedCoolingCapacityWatts");
        validateNonNegativeFinite(coolingDeficitWatts, "coolingDeficitWatts");
        if (!Double.isFinite(averageInletAirTemperatureCelsius)) throw new IllegalArgumentException("averageInletAirTemperatureCelsius must be finite");
        if (!Double.isFinite(averageExhaustAirTemperatureCelsius)) throw new IllegalArgumentException("averageExhaustAirTemperatureCelsius must be finite");
        if (!Double.isFinite(averageRecirculationFraction) || averageRecirculationFraction < 0.0 || averageRecirculationFraction > 1.0)
            throw new IllegalArgumentException("averageRecirculationFraction must be finite and between 0.0 and 1.0");
        if (usedCoolingCapacityWatts > availableCoolingCapacityWatts)
            throw new IllegalArgumentException("usedCoolingCapacityWatts must not exceed availableCoolingCapacityWatts");
        if (averageExhaustAirTemperatureCelsius < averageInletAirTemperatureCelsius)
            throw new IllegalArgumentException("averageExhaustAirTemperatureCelsius must not be below averageInletAirTemperatureCelsius");
        zoneCodes = List.copyOf(zoneCodes);
    }

    /**
     * Returns the fraction of available cooling capacity currently used by the
     * grouped zones.
     *
     * @return cooling load in the range {@code [0.0, 1.0]}
     */
    public double coolingLoad() {
        if (availableCoolingCapacityWatts == 0.0) return 0.0;
        return usedCoolingCapacityWatts / availableCoolingCapacityWatts;
    }

    /**
     * Returns the fraction of generated heat currently covered by cooling.
     *
     * <p>A group without generated heat returns {@code 1.0}, because there is no
     * thermal load to cover.</p>
     *
     * @return thermal coverage in the range {@code [0.0, 1.0]}
     */
    public double thermalCoverage() {
        if (generatedHeatWatts == 0.0) return 1.0;
        return usedCoolingCapacityWatts / generatedHeatWatts;
    }

    /**
     * Returns the average air-temperature increase across the grouped zones.
     *
     * @return average temperature increase in degrees Celsius
     */
    public double airTemperatureRiseCelsius() {
        return averageExhaustAirTemperatureCelsius - averageInletAirTemperatureCelsius;
    }

    /**
     * Returns whether the grouped zones have uncovered thermal load.
     *
     * @return {@code true} if the total cooling deficit is greater than zero
     */
    public boolean hasCoolingDeficit() {
        return coolingDeficitWatts > 0.0;
    }

    private static void validateNonNegativeFinite(double value, String name) {
        if (!Double.isFinite(value) || value < 0.0) throw new IllegalArgumentException(name + " must be finite and greater than or equal to 0.0");
    }
}