package com.cpz.sim.datacenter.snapshot;

import java.util.Objects;

/**
 * Represents the thermal and cooling result of a cooling zone at a simulation
 * tick.
 *
 * @param zoneCode cooling-zone code
 * @param generatedHeatWatts heat generated by the servers in the zone
 * @param availableCoolingCapacityWatts cooling capacity available to the zone
 * @param usedCoolingCapacityWatts cooling capacity used by the zone
 * @param coolingDeficitWatts heat that could not be covered by the available
 *        cooling capacity
 * @param supplyAirflowCubicMetersPerSecond supply airflow reaching the zone
 * @param exhaustAirflowCubicMetersPerSecond extraction airflow affecting the
 *        zone
 * @param inletAirTemperatureCelsius effective server inlet-air temperature
 * @param exhaustAirTemperatureCelsius resulting hot-air temperature
 * @param recirculationFraction fraction of exhaust air recirculated to the
 *        inlet
 *
 * @author CPZ
 */
public record CoolingZoneSnapshot(
        String zoneCode,
        double generatedHeatWatts,
        double availableCoolingCapacityWatts,
        double usedCoolingCapacityWatts,
        double coolingDeficitWatts,
        double supplyAirflowCubicMetersPerSecond,
        double exhaustAirflowCubicMetersPerSecond,
        double inletAirTemperatureCelsius,
        double exhaustAirTemperatureCelsius,
        double recirculationFraction
) {

    /**
     * Creates a cooling-zone snapshot.
     *
     * @throws NullPointerException if {@code zoneCode} is {@code null}
     * @throws IllegalArgumentException if the code is blank, a numeric value
     *         is invalid, used capacity exceeds available capacity, or the
     *         exhaust-air temperature is below the inlet-air temperature
     */
    public CoolingZoneSnapshot {
        Objects.requireNonNull(zoneCode, "zoneCode must not be null");
        if (zoneCode.isBlank()) throw new IllegalArgumentException("zoneCode must not be blank");
        validateNonNegativeFinite(generatedHeatWatts, "generatedHeatWatts");
        validateNonNegativeFinite(availableCoolingCapacityWatts, "availableCoolingCapacityWatts");
        validateNonNegativeFinite(usedCoolingCapacityWatts, "usedCoolingCapacityWatts");
        validateNonNegativeFinite(coolingDeficitWatts, "coolingDeficitWatts");
        validateNonNegativeFinite(supplyAirflowCubicMetersPerSecond, "supplyAirflowCubicMetersPerSecond");
        validateNonNegativeFinite(exhaustAirflowCubicMetersPerSecond, "exhaustAirflowCubicMetersPerSecond");
        if (!Double.isFinite(inletAirTemperatureCelsius)) throw new IllegalArgumentException("inletAirTemperatureCelsius must be finite");
        if (!Double.isFinite(exhaustAirTemperatureCelsius)) throw new IllegalArgumentException("exhaustAirTemperatureCelsius must be finite");
        if (!Double.isFinite(recirculationFraction) || recirculationFraction < 0.0 || recirculationFraction > 1.0)
            throw new IllegalArgumentException("recirculationFraction must be finite and between 0.0 and 1.0");
        if (usedCoolingCapacityWatts > availableCoolingCapacityWatts)
            throw new IllegalArgumentException("usedCoolingCapacityWatts must not exceed availableCoolingCapacityWatts");
        if (exhaustAirTemperatureCelsius < inletAirTemperatureCelsius)
            throw new IllegalArgumentException("exhaustAirTemperatureCelsius must not be below inletAirTemperatureCelsius");
    }

    /**
     * Returns whether the zone has uncovered thermal load.
     *
     * @return {@code true} if the cooling deficit is greater than zero
     */
    public boolean hasCoolingDeficit() {
        return coolingDeficitWatts > 0.0;
    }

    /**
     * Returns the fraction of available cooling capacity currently used.
     *
     * <p>A zone without available cooling capacity returns {@code 0.0}. Its
     * uncovered thermal load remains observable through
     * {@link #coolingDeficitWatts()}.</p>
     *
     * @return cooling-capacity utilization in the range {@code [0.0, 1.0]}
     */
    public double coolingCapacityUtilization() {
        if (availableCoolingCapacityWatts == 0.0) return 0.0;
        return usedCoolingCapacityWatts / availableCoolingCapacityWatts;
    }

    /**
     * Returns the air-temperature increase across the zone.
     *
     * @return temperature increase in degrees Celsius
     */
    public double airTemperatureRiseCelsius() {
        return exhaustAirTemperatureCelsius - inletAirTemperatureCelsius;
    }

    private static void validateNonNegativeFinite(double value, String name) {
        if (!Double.isFinite(value) || value < 0.0) throw new IllegalArgumentException(name + " must be finite and greater than or equal to 0.0");
    }

}