package com.cpz.sim.datacenter.cooling;

import java.util.List;
import java.util.Objects;

/**
 * Contains the thermal input processed by the cooling system during a tick.
 *
 * @param tickIndex       index of the simulation tick
 * @param serverHeatLoads instantaneous heat loads generated by the servers
 *
 * @author CPZ
 */
public record CoolingTickInput(
        long tickIndex,
        double deltaSeconds,
        List<ServerHeatLoad> serverHeatLoads
) {

    public static final double DEFAULT_DELTA_SECONDS = 60.0;

    public CoolingTickInput(long tickIndex, List<ServerHeatLoad> serverHeatLoads) {
        this(tickIndex, DEFAULT_DELTA_SECONDS, serverHeatLoads);
    }

    public CoolingTickInput {
        if (tickIndex < 0L) throw new IllegalArgumentException("tickIndex must be greater than or equal to zero");
        if (!Double.isFinite(deltaSeconds) || deltaSeconds <= 0.0) throw new IllegalArgumentException("deltaSeconds must be finite and greater than zero");
        Objects.requireNonNull(serverHeatLoads, "serverHeatLoads must not be null");
        if (serverHeatLoads.stream().anyMatch(Objects::isNull)) throw new NullPointerException("serverHeatLoads must not contain null elements");
        serverHeatLoads = List.copyOf(serverHeatLoads);
    }
}