package com.cpz.sim.datacenter.cooling;

import java.util.List;
import java.util.Objects;

/**
 * Contains the thermal input processed by the cooling system during a tick.
 *
 * @param tickIndex       index of the simulation tick
 * @param serverHeatLoads instantaneous heat loads generated by the servers
 *
 * @author CPZ
 */
public record CoolingTickInput(
        long tickIndex,
        List<ServerHeatLoad> serverHeatLoads
) {

    /**
     * Creates a validated and immutable cooling tick input.
     *
     * @throws IllegalArgumentException if {@code tickIndex} is negative
     * @throws NullPointerException     if {@code serverHeatLoads} is
     *                                  {@code null} or contains a null element
     */
    public CoolingTickInput {
        if (tickIndex < 0L) throw new IllegalArgumentException("tickIndex must be greater than or equal to zero");
        Objects.requireNonNull(serverHeatLoads,"serverHeatLoads must not be null");
        if (serverHeatLoads.stream().anyMatch(Objects::isNull))
            throw new NullPointerException("serverHeatLoads must not contain null elements");
        serverHeatLoads = List.copyOf(serverHeatLoads);
    }
}