package com.cpz.sim.datacenter.cooling;

import com.cpz.sim.datacenter.model.ServerLocation;

import java.util.Objects;

/**
 * Represents the instantaneous heat load generated by a server.
 *
 * <p>The generated heat is expressed in watts and is expected to be
 * non-negative and finite.</p>
 *
 * @param serverLocation    location of the server generating the heat
 * @param generatedHeatWatts instantaneous heat generated by the server,
 *                           expressed in watts
 *
 * @author CPZ
 */
public record ServerHeatLoad(
        ServerLocation serverLocation,
        double generatedHeatWatts
) {

    /**
     * Creates a validated server heat load.
     *
     * @throws NullPointerException     if {@code serverLocation} is {@code null}
     * @throws IllegalArgumentException if {@code generatedHeatWatts} is negative
     *                                  or not finite
     */
    public ServerHeatLoad {
        Objects.requireNonNull(serverLocation, "serverLocation must not be null");
        if (!Double.isFinite(generatedHeatWatts)) throw new IllegalArgumentException("generatedHeatWatts must be finite");
        if (generatedHeatWatts < 0.0) throw new IllegalArgumentException("generatedHeatWatts must be greater than or equal to zero");
    }
}